### ISSUE TITLE
Check if schemas are installed?

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#198]
Should we check if certain schemas are installed? And if not disable the corresponding section?
For example if one disables dash to dock
Or the new multitasking page is only available in 22.04 daily so far
Alternatively, since settings is still in early alpha, we could start to think about releases a bit more "smart" and make different releases for different distro versions

CC @jpnurmi @Jupi007

**Comment by Jupi007** [comment]
Imo, make missing schemas related section disabled could be better (and simpler to maintain).

For example, I don't use DashToDock and so I don't have related shemas. It should be disabled for me.

**Comment by jpnurmi** [comment]
Totally agree, the app should not throw even if any schema is missing. :+1: Make sure to use `fooSettings?.bar` everywhere and never assume them being available/non-nullable (`fooSettings!.bar`).

**Comment by mivoligo** [comment]
What would be the best way to handle that?

So far if a schema was not found, a getter in a model was nullable and a widget with settings for that schema would build empty SizedBox if the value was null. That made the widget invisible in the app UI. 

Problem is that we can see the "red screen of death" and null values error for a split second due to the time taken by the service to read the schema values. @Feichtmeier suggested we should better not use nullable getters and have a default value in case of null (when schema doesn't exist). When we do that the problem with the red screen is gone but we render all settings widgets even if a schema is not found.

**Comment by jpnurmi** [comment]
Using default values is safer but then you can't detect/visualize it in the UI.

In general, personally, I'd prefer things to be disabled when they are not available because dynamically appearing UI elements tend to cause flicker while the data is being asynchronously initialized. There are probably cases where it doesn't make sense to show something if it's not available, though, but I'd keep such visibility conditions to the minimum.

https://github.com/Feichtmeier/settings/pull/191#issuecomment-992918631

**Comment by Feichtmeier** [comment]
So we should rather check for null and only show stuff in the view if the model getter do not return null?

**Comment by mivoligo** [comment]
I'm fine with displaying them as disabled if a schema is missing but not sure how to achieve tbh :slightly_smiling_face:

**Comment by jpnurmi** [comment]
Disabling widgets is a bit clumsy in Flutter because one mostly needs to conditionally pass null to various `onPressed`, `onTap`, `onChanged`, `onSelected` handlers. There are only a few widgets that have a nice and clean `enabled` property. Nevertheless, `IconTheme` and `DefaultTextStyle` can be used to complete the looks by setting disabled colors for non-interactive labels and icons.

For example:
<details><summary>example.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:yaru/yaru.dart';

void main() {
  runApp(
    MaterialApp(
      home: const HomePage(),
      theme: yaruLight,
    ),
  );
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  bool _switchValue = true;
  bool _checkboxValue = true;
  bool _radioValue = true;
  double _sliderValue = 0.5;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Enabled vs. disabled'),
      ),
      body: Center(
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            _buildColumn(context, enabled: true),
            const SizedBox(width: 24),
            _buildColumn(context, enabled: false),
          ],
        ),
      ),
    );
  }

  Widget _buildColumn(BuildContext context, {bool enabled = true}) {
    return IconTheme(
      data: IconThemeData(
        color: enabled ? null : Theme.of(context).disabledColor,
      ),
      child: DefaultTextStyle(
        style: TextStyle(
          color: enabled
              ? Theme.of(context).textTheme.bodyText1!.color
              : Theme.of(context).disabledColor,
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(enabled ? 'Enabled' : 'Disabled'),
            ElevatedButton(
              onPressed: enabled ? () {} : null,
              child: const Text('ElevatedButton'),
            ),
            OutlinedButton(
              onPressed: enabled ? () {} : null,
              child: const Text('OutlinedButton'),
            ),
            TextButton(
              onPressed: enabled ? () {} : null,
              child: const Text('TextButton'),
            ),
            Row(
              children: [
                IconButton(
                  onPressed: enabled ? () {} : null,
                  icon: const Icon(Icons.flutter_dash),
                ),
                const Text('IconButton'),
              ],
            ),
            PopupMenuButton<String>(
              itemBuilder: (context) {
                return [
                  const PopupMenuItem(child: Text('Foo')),
                  const PopupMenuItem(child: Text('Bar')),
                  const PopupMenuItem(child: Text('Baz')),
                ];
              },
              enabled: enabled,
              onSelected: null,
              child: const Text('PopupMenuButton'),
            ),
            DropdownButton<int>(
              value: 1,
              onChanged: enabled ? (_) {} : null,
              selectedItemBuilder: (context) => List.generate(3, (_) {
                return const DropdownMenuItem(child: Text('DropdownButton'));
              }),
              items: const [
                DropdownMenuItem(child: Text('Foo'), value: 1),
                DropdownMenuItem(child: Text('Bar')),
                DropdownMenuItem(child: Text('Baz')),
              ],
            ),
            SizedBox(
              width: 144,
              child: ListTile(
                title: const Text('ListTile'),
                enabled: enabled,
                onTap: () {},
              ),
            ),
            Row(
              children: [
                Switch(
                  value: _switchValue,
                  onChanged:
                      enabled ? (v) => setState(() => _switchValue = v) : null,
                ),
                const Text('Switch'),
              ],
            ),
            Row(
              children: [
                Checkbox(
                  value: _checkboxValue,
                  onChanged: enabled
                      ? (v) => setState(() => _checkboxValue = v!)
                      : null,
                ),
                const Text('Checkbox'),
              ],
            ),
            Row(
              children: [
                Radio<bool>(
                  value: true,
                  toggleable: true,
                  groupValue: _radioValue,
                  onChanged: enabled
                      ? (v) => setState(() => _radioValue = v ?? false)
                      : null,
                ),
                const Text('Radio'),
              ],
            ),
            Slider(
              value: _sliderValue,
              onChanged:
                  enabled ? (v) => setState(() => _sliderValue = v) : null,
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

![Screenshot from 2022-01-05 09-19-49](https://user-images.githubusercontent.com/140617/148184044-3d68e6d4-1f43-4d4b-b8d1-61fa8e158ee4.png)

**Comment by mivoligo** [comment]
Sorry, I wasn't clear probably. I get how to disable widgets in Flutter in general. What I'm not sure is: on what basis we are going to have them disabled in this app. If we don't allow getters to be nullable if a schema doesn't exist, how the widget would know if it should be disabled or not? Or are we allowing nullable getters and instead of hiding widgets, we make them look disabled?

**Comment by jpnurmi** [comment]
Oh, it was a misunderstanding. :smile: Yeah, as commented above, the properties must be nullable indeed to be able to detect missing values. I'd definitely go with nullable values because that's the natural way to present missing values, after all. :+1: Returning some arbitrary default values just to be able to make the properties non-nullable might be safer, but then it becomes impossible to detect missing values in the UI. :-1:

**Comment by mivoligo** [comment]
OK, thanks! 
I see the widgets are in a separate package now. So we need to start there. I could try and do a PR later on.

**Comment by Feichtmeier** [comment]
Thanks guys for analyzing and providing disabled visuals via yaru_widgets! Closing
