### ISSUE TITLE
"Do not disturb" switch has opposite value than expected

### ISSUE THREAD

**Issue by mivoligo** [Feichtmeier/settings#9]
First of all, this is fantastic work @Feichtmeier and @Jupi007 I'll try to contribute after my holiday :)

I've noticed on the Notifications page the switch "Do not disturb" displays wrong value. Screenshot with comparison to the Gnome control center app
![Zaznaczenie_001](https://user-images.githubusercontent.com/1629120/125682566-1c4484c0-49d0-47b8-bfcd-c256fe438319.png)

**Comment by Feichtmeier** [comment]
Hi 👋 
Thanks :) It is all building up on @jp-nurmi 's gsettings dart file.
Soon^tm it will use a dart native package by canonical but currently this is totally fine since there are soooo many pages to implement.

Thanks for your will to contribute! Feel free to grab any of the existing pages or whatever you want to change / improve.

I tried to gather some common patterns that can be used for more pages inside the widgets dir. If you find more patterns please feel free to add them :)

On topic of the issue: I think the gsetting here is more like "show global notifications". And the label says the opposite. So one need to either invert the boolean or change the label to match the gsetting :)

**Comment by Jupi007** [comment]
And what about create an `InvertedBoolSettingsRow`?

**Comment by Feichtmeier** [comment]
we could put an "invertedValue" property or something

**Comment by mivoligo** [comment]
Thanks for the answers. I'll get in touch when I'm ready.
